name: Demo Typescript action

on:
  workflow_dispatch:    
  push:
    paths: .github/workflows/demo-ts-action.yml

jobs:
  container_action:
    runs-on: ubuntu-latest
    steps:
      - uses: lfraile-git-school/typescript-action@v1.2
        with:
          milliseconds: 2000
